/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

@interface NTContactsUtil : NSObject {
}
+(id)rac_getDist1CanBeInvited;
+(id)rac_getDist1Contacts;
+(id)getDist1Contacts;
+(id)getDist1ContactsByMMIDs:(id)mmids;
+(void)updateD1Contacts:(id)contacts;
+(void)storeUpdatedUsers:(id)users toDB:(id)db;
+(void)parseUser:(id)user toDB:(id)db;
+(void)parseUsers:(id)users;
+(void)asynStoreUserToDB:(id)db;
+(void)storeUserToDB:(id)db;
+(BOOL)isAnonymousUser:(id)user;
@end

