/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@class NSMutableArray, NSString;

@interface NTGossipModel : NSObject{}

@property(assign, nonatomic) int type;
@property(assign, nonatomic) int piyao;
@property(assign, nonatomic) int localTaskType;
@property(retain, nonatomic) NSString* hashId;
@property(retain, nonatomic) NSString* localErrorMsg;
@property(assign, nonatomic) int localStatus;
@property(assign, nonatomic) int lastReplyToid;
@property(retain, nonatomic) NSString* lastTempComment;
@property(retain, nonatomic) NSMutableArray* images;
@property(retain) NSMutableArray* hotcomments;
@property(retain) NSMutableArray* comments;
@property(readonly, assign, nonatomic) NSString* shareTitleStr;
@property(readonly, assign, nonatomic) NSString* shareStr;
@property(readonly, assign, nonatomic) NSString* spreadStr;
@property(readonly, assign, nonatomic) NSString* commentStr;
@property(readonly, assign, nonatomic) NSString* yesStr;
//@property(retain, nonatomic) MMRichText* richText;
@property(assign, nonatomic) int show_tag_in_list;
@property(retain, nonatomic) NSString* tags_v2;
@property(retain, nonatomic) NSString* btnUrl2;
@property(retain, nonatomic) NSString* btnUrl1;
@property(assign, nonatomic) int btnType2;
@property(assign, nonatomic) int btnType1;
@property(retain, nonatomic) NSString* btnText2;
@property(retain, nonatomic) NSString* btnText1;
@property(assign, nonatomic) int ishint;
@property(retain, nonatomic) NSString* tags;
@property(retain, nonatomic) NSString* note;
@property(retain, nonatomic) NSString* shareUrl;
@property(assign, nonatomic) int ysize;
@property(assign, nonatomic) int xsize;
@property(retain, nonatomic) NSString* fpath;
@property(retain, nonatomic) NSString* mmid;
@property(retain, nonatomic) NSString* author;
@property(retain, nonatomic) NSString* time;
@property(retain, nonatomic) NSString* topic;
@property(assign, nonatomic) int hasYes;
@property(assign, nonatomic) int yesCnt;
@property(assign, nonatomic) int spreadCnt;
@property(assign, nonatomic) int shareCnt;
@property(assign, nonatomic) int haveMoreCmt;
@property(assign, nonatomic) int commentCnt;
@property(retain, nonatomic) NSString* text;
+(id)modelFromDic:(id)dic;
+(id)gossipModelsFromData:(id)data;
+(id)gossipModelFromData:(id)data;

@end

