/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

@interface RACSubscriber : NSObject {
	id _next;
	id _error;
	id _completed;
}

@property(copy, nonatomic) id completed;
@property(copy, nonatomic) id error;
@property(copy, nonatomic) id next;

+(id)subscriberWithNext:(id)next error:(id)error completed:(id)completed;
-(void)didSubscribeWithDisposable:(id)disposable;
-(void)sendCompleted;
-(void)sendError:(id)error;
-(void)sendNext:(id)next;
-(id)init;
@end

